### PR TITLE
fix #27

### LINKED ISSUE #27: Editing new file crashes
If I try to edit a new file, before saving it, I get an error.

1. Edit new file (don't save it)
2. Type something.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.3.0

### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/andre/.atom/packages/language-elm/lib/provider.js:256

Error: No elm-oracle suggestions
    at noOutputFromOracleError (/Users/andre/.atom/packages/language-elm/lib/provider.js:227:10)
    at parseOutput (/Users/andre/.atom/packages/language-elm/lib/provider.js:256:11)
    at provideSuggestions (/Users/andre/.atom/packages/language-elm/lib/provider.js:59:15)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

### Commands

```
     -0:48.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:47.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -0:47.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "linter-xmllint"
    ]
  },
  "language-elm": {
    "elmOraclePath": "/Users/andre/.atom/packages/language-elm/node_modules/elm-oracle/bin/elm-oracle"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.4.2
autocomplete-erlang, v1.1.1
autocomplete-python, v0.10.4
highlight-selected, v0.11.1
language-elixir, v0.5.2
language-elm, v1.3.0
language-erlang, v3.0.0
linter, v1.11.1
linter-clang, v3.3.0
linter-lua, v1.0.0
linter-pyflakes, v0.0.5
linter-pylint, v1.0.3
linter-python-pep8, v0.2.0
linter-shellcheck, v1.0.2
minimap, v4.16.0
python-isort, v0.0.7

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by despairblue**
Thoughts and comments welcome. Not sure if this is the best way.

### CODE REVIEW

File: lib/provider.js [hunk 1]
```diff
@@ -253,7 +252,11 @@ const parseOutput = (text) => {
   text = text && text.slice(0, text.indexOf('\n'));
 
   if (!text) {
-    throw noOutputFromOracleError();
+    atom.notifications.addWarning('Elm Autocomplete Error', {
```
Comment (brianegan) [inline lib/provider.js]: Hrm, I'm not so sure about this change. I'd like to keep throwing errors at this point so we can continue to catch problems from different users and fix them at their source, rather than simply hiding the fact that there is an error. Good news! You've fixed the root cause of the problem above :) So I'd prefer to revert this part of the change. Thoughts?

File: lib/provider.js [hunk 2]
```diff
@@ -33,14 +33,18 @@ module.exports = {
 
   getSuggestions({editor, bufferPosition, scopeDescriptor}) {
     const prefix = getPrefix(editor, bufferPosition);
+    const filePath = editor.getPath();
 
     if (shouldPreventAutocomplete(prefix)) {
       return null;
     }
 
+    if (filePath === undefined) {
```
Comment (brianegan) [inline lib/provider.js]: Nice! This looks like the root cause of the problem. Let's go ahead and clean it up just a bit. Rather than having another `if` statement here that could return null, let's go ahead and pass the `filePath` into the `shouldPreventAutoComplete` function and do all of the checks in there.

e.g.

```js
if shouldPreventAutoComplete(prefix, filePath) {
  return null;
}
```

And then `shouldPreventAutoComplete` could looks like this:

```js
const shouldPreventAutocomplete = (prefix, filePath) => {
  return prefix.length < atom.config.get('language-elm.minCharsForAutocomplete')
      || !atom.config.get('language-elm.autocompleteEnabled')
      || !filePath; // This is the important part! No need to check explicitly for undefined, as undefined is a "falsy" value
}
```

**Comment by brianegan** [comment]
Thanks so much for contributing! I've provided some comments on changes I think would be improvements to this code. Happy to hear opposing views if you disagree with any part.

File: lib/provider.js (hunk 1 above)
Comment (despairblue) [inline lib/provider.js]: Ok, but then we would need to catch the case that the editor has a filePath but is not saved yet (as happens when creating editors with [advanced-open-file](https://atom.io/packages/advanced-open-file)). That's actually where this PR came from. This error was thrown for every letter that I inserted :smile: .

File: lib/provider.js (hunk 2 above)
Comment (despairblue) [inline lib/provider.js]: Sounds good. Will do.

Though I do like to check for `undefined` explicitly since a lot of things are falsy in JS, e.g. an `''` or `0`.

Comment (brianegan) [inline lib/provider.js]: Sure thing, oftentimes good to be explicit :) In this case I think it's safe to assume all falsy values are bad filePaths, so let's keep the `!filePath`.

File: lib/provider.js (hunk 1 above)
Comment (brianegan) [inline lib/provider.js]: Oh wacky, hadn't thought of that case! The filepath exists before the file is saved!?

keanu-woah

In that case, let's create a `fileExists` function that:

  1. Ensures the filepath looks legit
  2. Checks to see if the file actually exists (using node's fs#statsSync).

Then we can use that in the `shouldPreventAutoComplete` function. How does that sound?

Comment (brianegan) [inline lib/provider.js]: p.s. Thanks again for contributing :)

File: lib/provider.js [hunk 3]
```diff
@@ -20,9 +21,18 @@ const getPrefix = (editor, bufferPosition) => {
...
+    || !atom.config.get('language-elm.autocompleteEnabled')
+    || !filePath;
+
+  if (shouldPrevent) {
+    return Promise.resolve(shouldPrevent);
+  } else {
+    return new File(filePath)
+      .exists()
+      .then(exists => !exists);
+  }
```
Comment (despairblue) [inline lib/provider.js]: How about this?

File: lib/provider.js (hunk 1 above)
Comment (despairblue) [inline lib/provider.js]: No problem. I updated this part! What do you think?

File: lib/provider.js (hunk 3 above)
Comment (brianegan) [inline lib/provider.js]: Oh nice! Didn't know about the File api :) Good stuff.

**Comment by brianegan** [comment]
Sorry about the delay -- getting back to work after the holidays, but great contribution! Thanks for the PR :)

**Comment by brianegan** [comment]
Hey @edubkendo -- if you get a chance, could you push up a new release for this fix? Thanks :)

**Comment by edubkendo** [comment]
lol was just about to ask, is this a breaking change or not?

**Comment by brianegan** [comment]
Nope just fixes a bug :) Dang you're on top if it, haha

**Comment by edubkendo** [comment]
done ;P
